name: Daily Quiz Bot

on:
  workflow_dispatch: # इसे मैन्युअल रूप से चलाने के लिए
  schedule:
    # यह शेड्यूल दिन में 15 बार चलेगा (सुबह 9 बजे से रात 8 बजे तक)
    - cron: '30 3 * * *'  # सुबह 9:00 बजे IST
    - cron: '15 4 * * *'  # सुबह 9:45 बजे IST
    - cron: '0 5 * * *'   # सुबह 10:30 बजे IST
    - cron: '45 5 * * *'  # सुबह 11:15 बजे IST
    - cron: '30 6 * * *'  # दोपहर 12:00 बजे IST
    - cron: '15 7 * * *'  # दोपहर 12:45 बजे IST
    - cron: '0 8 * * *'   # दोपहर 1:30 बजे IST
    - cron: '45 8 * * *'  # दोपहर 2:15 बजे IST
    - cron: '30 9 * * *'  # दोपहर 3:00 बजे IST
    - cron: '15 10 * * *' # दोपहर 3:45 बजे IST
    - cron: '0 11 * * *'  # शाम 4:30 बजे IST
    - cron: '45 11 * * *' # शाम 5:15 बजे IST
    - cron: '30 12 * * *' # शाम 6:00 बजे IST
    - cron: '15 13 * * *' # शाम 6:45 बजे IST
    - cron: '0 14 * * *'  # शाम 7:30 बजे IST

jobs:
  send-quiz:
    runs-on: ubuntu-latest
    permissions:
      contents: write # यह लाइन ज़रूरी है
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot pandas

      - name: Run quiz script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python quiz_bot.py
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@github.com'
          
      - name: Commit and push if changed
        run: |
          git add sent_questions.txt
          git diff --staged --quiet || (git commit -m "Update sent questions list" && git push)
